stashing
code-dot-org/analytics pull request #100
Opened 2024-03-06 20:26 UTC by jordan-springer

# Description

Updating teachers mart with coteacher data

## Links

Jira ticket(s): [dataops-548](https://codedotorg.atlassian.net/browse/DATAOPS-548)

## Testing story

- [ ] Does your change include appropriate tests on key columns?
      eg.
      - `not_null`
      - `unique`
      - `dbt_utils.unique_combination_of_columns: , ["value","value","value"...]

**Note: when submitting a new model for review please make sure the following have been tested:**

1. The model compiles (`dbt build -m 'your_model'`)
         or: _has the dbt Cloud job succeeded?_
3. The model runs (`dbt run -m 'your_model'`)
4. The model produces accessible data in the DW (`select 1 from 'your_model'`)

## Privacy

- [ ] 1.	Does this change involve the collection, use, or sharing of new Personal Data?
- [ ] 2.    Do these data exist in the appropriate schema(s)? 
- [ ] 3.	Does this change involve a new or changed use or sharing of existing Personal Data?
- [ ] 4.    Consider: will this data be visible on Tableau? will this data be surfaced in a report exported from Trevor?
- [ ] 5.    If yes to any of the above, please list the models, columns, and justification below:
      i.
      ii.
      iii. 

## PR Checklist:
**Note: if these are not all checked, the PR will be sent back.**

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code adheres to [style guide](https://docs.getdbt.com/best-practices/how-we-style/0-how-we-style-our-dbt-projects)👀 and is **[DRY](https://docs.getdbt.com/terms/dry)**
- [ ] Code is well-commented (**please do not leave extraneous commentary in model code, if it is for the purpose of documentation, please relocate accordingly)
- [ ] Appropriate documentation has been provided (see `.yml.`, did `dbt docs generate` succeed?)
- [ ] New features are translatable or updates will not break up/downstream models
- [ ] Relevant documentation has been added or updated (i.e. `dbt docs` has been updated successfully on [Github Pages](code-dot-org.github.io/analytics/)
- [ ] Pull Request is labeled appropriately (eg. `chore/`, `feature/`, `fix/`)
- [ ] Follow-up work items (including potential tech debt) are tracked and linked (if applicable)

2024-03-07 21:56 UTC, nataliazm99 requested changes
Overall, same comments as [here](https://codedotorg.atlassian.net/browse/DATAOPS-548?focusedCommentId=27408) for what needs to be done to capture the co-teacher work. 
Some individual observations in-code

2024-03-07 21:56 UTC, nataliazm99 commented on dbt/models/marts/sections/dim_section_instructors.sql
> +        case when invited_by_id is null -- wasn't invited (is the teacher)
```suggestion
--        case when invited_by_id is null -- wasn't invited (is the teacher)
```

2024-03-07 21:56 UTC, nataliazm99 commented on dbt/models/marts/sections/dim_section_instructors.sql
> +            then 1 else 0
```suggestion
--            then 1 else 0 
```

2024-03-07 21:56 UTC, nataliazm99 commented on dbt/models/marts/sections/dim_section_instructors.sql
> +        section_instructors.is_section_owner,
```suggestion
 --       section_instructors.is_section_owner,
 case when section_instructors.instructor_id = sections.teacher_id then 1 else 0 is_section_owner
```
A couple of weeks ago I ran into some use cases that highlighted this is the way to identify section owners. Some explanation of the use cases in the threads linked [here ](https://codedotorg.slack.com/archives/C05B9AWTTD5/p1708555911819539)

2024-03-07 21:56 UTC, nataliazm99 commented on dbt/models/marts/sections/dim_section_instructors.sql
> +        end as is_section_owner
```suggestion
--        end as is_section_owner
```

2024-03-07 21:56 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_teachers.sql
> +    where teacher_id in (select teacher_id from teachers)
I don't think this is possible because the platform only allows to create sections or invite users with accounts of type teacher, which is the filter going into the 'teachers' CTE

2024-03-07 21:56 UTC, nataliazm99 commented on dbt/models/marts/sections/dim_section_instructors.sql
> +    from {{ ref('stg_dashboard__section_instructors') }}
I can't find the definition of this table, but it seems like it is only bringing in records where `invited_by_teacher_id is not null`. This restriction needs to be lifted as the comment below explains there are cases where multiple teachers might be co-teaching a section even without an invitation if they have joined through an LMS platform. The comment below has the thread with examples of this behavior.

2024-03-07 21:56 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_teachers.sql
> +    from {{ ref('dim_section_instructors') }}
Let's align on terminology: Co-teachers are multiple teachers who teach the same section. The section owner is the one with the matching user_id in dim_sections, the other teacher(s) might be the ones usually referred to as co-teachers.

2024-03-07 21:56 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_teachers.sql
> +        case when not coteachers.is_section_owner then 1 else 0 end as is_coteacher
``` suggestion
--        case when not coteachers.is_section_owner then 1 else 0 end as is_coteacher
```
One teacher might be a section owner for some sections and co-teachers (not owners) for others, so flagging them as co-teachers overall might lead to confusion. This will be more useful for records with section and teacher association

2024-03-21 21:31 UTC, nataliazm99 requested changes
The tables that should be including co-teachers don't seem to be including them.
There are a number of changes to tables that are already in production, those should be considered carefully as they affect work already in use by end users. If these changes are going through they should be listed so they can be communicated clearly.
There are changes to values that we have been using across the codebase that should not be changed, I've noted those.

2024-03-21 21:31 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_teachers.sql
Are there any changes here that will change the table currently live in production? If so, please note the changes so we can communicate hem to people using trevor.

2024-03-21 21:31 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_teachers.sql
> +-- scope: all teachers, no including co-teachers
Co teachers are included here, because they have a user account type teacher
```suggestion
-- scope: all teachers
```

2024-03-21 21:31 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_teachers.sql
> +-- scope: all teachers, no including co-teachers
This code can be used to validate that co-teachers are included

```select 
si.section_id 
, si.teacher_id 
, si.is_section_owner 
, t.teacher_id 
from dbt_natalia.stg_dashboard__section_instructors si
left join dbt_natalia.dim_teachers t on si.teacher_id = t.teacher_id
where si.section_id in (
4410895
, 4476680
, 3785088
, 4769654
, 4775209
, 4790631)
order by si.section_id , si.teacher_id ;```

2024-03-21 21:31 UTC, nataliazm99 commented on dbt/models/marts/users/dim_users.sql
Why are `is_urg` and `sign_in_count` being dropped? These are important fields, especially `is_urg`

2024-03-21 21:31 UTC, nataliazm99 commented on dbt/models/staging/dashboard/stg_dashboard__section_instructors.sql
Would be useful to ask Bryan if this table is recording a historic log of changes to the teacher's activity: does it create a new record when the status changes? Or does the status overwrites the previous one? If it overwrites we could lose the history of active teachers once they are removed from a section.

2024-03-21 21:31 UTC, nataliazm99 commented on dbt/models/staging/dashboard/stg_dashboard__user_geos.sql
> -        us_intl,
I think we should leave us_intl (us|intnl) as this is a field many people are already using in trevor because the region spelled out is the most common way data is presented, much more common than the 1/0 flag in is_international. Please do not remove it.

2024-03-21 21:31 UTC, nataliazm99 commented on dbt/models/staging/dashboard_pii/stg_dashboard_pii__users.sql
> +            when races like '%,%' then 'two or more'
```suggestion
            when races like '%,%' then 'two or more_non_urg'
```
If it is not caught by the case above, it is two+race, non urg. And we need to be able to differentiate. Without describing as 'non-urg' it appears as if it contains both urg and non-urg

2024-03-21 21:31 UTC, nataliazm99 commented on dbt/models/staging/dashboard_pii/stg_dashboard_pii__users.sql
> +            -- when races is null then 'n/a'
```suggestion
            -- when races is null then 'not_collected'
```
we use 'not collected' because it is different from 'no_response;, using 'n/a' could be either no response or not collected. Please don't change this. Many calculations not yet in hydrone use this decoding and the differentiation is important when communicating data.

2024-03-21 21:31 UTC, nataliazm99 commented on dbt/models/staging/dashboard_pii/stg_dashboard_pii__users.sql
> +            -- else races -- Additional logic may be required here
```suggestion
            else races -- Additional logic may be required here
```
The current logic is not returning race groups other than hispanic and the two+ groups. It should bring white, black, etc.

2024-03-21 21:31 UTC, nataliazm99 commented on dbt/models/staging/dashboard_pii/stg_dashboard_pii__users.sql
> +            then lower(gender)
```suggestion
when gender = 'n' then 'nb' -- non-binary
            when gender = 'o' then 'nl' -- not listed 
            when lower(gender) in ('m','f') then lower(gender)
            ```
            
          These are conventions we use elsewhere, we don't need to change them.

2024-03-21 21:31 UTC, nataliazm99 commented on dbt/models/staging/dashboard_pii/stg_dashboard_pii__users.sql
> +            else null
```suggestion
            else 'no_response'
```
o response means they didn't enter anything, this is useful for data communication

2024-03-25 18:22 UTC, jordan-springer commented on dbt/models/staging/dashboard_pii/stg_dashboard_pii__users.sql
> +            -- when races is null then 'n/a'
```suggestion
            when races is null then 'not collected'
```

2024-04-04 02:05 UTC, closed without merging