Adding us_state column to models
code-dot-org/analytics pull request #113
Opened 2024-05-10 20:33 UTC by jordan-springer

# Description

tl;dr -- extracted the "state" value from `users_pii.properties` to model in Hydrone, now available if needed in `dim_users`

## Links

Jira ticket(s): [dataops-916](https://codedotorg.atlassian.net/browse/DATAOPS-619)

## Testing story

- [ ] Does your change include appropriate tests on key columns?
      eg.
      - `not_null`
      - `unique`
      - `dbt_utils.unique_combination_of_columns: , ["value","value","value"...]

**Note: when submitting a new model for review please make sure the following have been tested:**

1. The model compiles (`dbt build -m 'your_model'`)
         or: _has the dbt Cloud job succeeded?_
3. The model runs (`dbt run -m 'your_model'`)
4. The model produces accessible data in the DW (`select 1 from 'your_model'`)

## Privacy

- [ ] 1.	Does this change involve the collection, use, or sharing of new Personal Data?
- [ ] 2.    Do these data exist in the appropriate schema(s)? 
- [ ] 3.	Does this change involve a new or changed use or sharing of existing Personal Data?
- [ ] 4.    Consider: will this data be visible on Tableau? will this data be surfaced in a report exported from Trevor?
- [ ] 5.    If yes to any of the above, please list the models, columns, and justification below:
      i.
      ii.
      iii. 

## PR Checklist:
**Note: if these are not all checked, the PR will be sent back.**

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code adheres to [style guide](https://docs.getdbt.com/best-practices/how-we-style/0-how-we-style-our-dbt-projects)👀 and is **[DRY](https://docs.getdbt.com/terms/dry)**
- [ ] Code is well-commented (**please do not leave extraneous commentary in model code, if it is for the purpose of documentation, please relocate accordingly)
- [ ] Appropriate documentation has been provided (see `.yml.`, did `dbt docs generate` succeed?)
- [ ] New features are translatable or updates will not break up/downstream models
- [ ] Relevant documentation has been added or updated (i.e. `dbt docs` has been updated successfully on [Github Pages](code-dot-org.github.io/analytics/)
- [ ] Pull Request is labeled appropriately (eg. `chore/`, `feature/`, `fix/`)
- [ ] Follow-up work items (including potential tech debt) are tracked and linked (if applicable)

2024-05-10 21:40 UTC, jordan-springer commented on dbt/models/staging/dashboard_pii/base/base_dashboard_pii__users.sql
> +    -- where user_type is not null
```suggestion
    where user_type is not null 
```

2024-05-10 21:41 UTC, jordan-springer reviewed
lgtm

2024-05-17 12:31 UTC, bakerfranke requested changes

2024-05-17 12:31 UTC, bakerfranke commented on dbt/models/staging/dashboard_pii/base/base_dashboard_pii__users.sql
> +             true)                  as us_state
We've never used this state extraction from user properties to associate a state with a user before.  Are we sure we know the source of it?

In the past we've just used the state assigned by user_geos - it carries state (and sometimes city) if in the U.S.

I think you should double-check to see if this `us_state` aligns with the `user_geo.state` and/or figure out the source of this one.

2024-05-17 12:31 UTC, bakerfranke commented on dbt/models/marts/users/dim_users.sql
> +        users_pii.us_state,
why not just use `ug.state` ?

2024-05-18 03:54 UTC, jordan-springer commented on dbt/models/staging/dashboard_pii/base/base_dashboard_pii__users.sql
> +             true)                  as us_state
see ticket here: https://codedotorg.atlassian.net/browse/DATAOPS-668

2024-05-18 03:56 UTC, jordan-springer commented on dbt/models/marts/users/dim_users.sql
> +        users_pii.us_state,
this is user-entered, it is needed for CPA. `ug.state` is based on IP

2024-05-31 20:52 UTC, jordan-springer commented on dbt/models/marts/users/dim_users.sql
> +        users_pii.us_state,
this seems unnecessary, the field is stored as `user_state`, we can describe its nature in the docs

2024-05-31 20:53 UTC, jordan-springer commented
@nataliazm99 what about states outside of the 50 US states?

2024-05-31 21:16 UTC, jordan-springer commented
!data looks good(
![image](https://github.com/code-dot-org/analytics/assets/38662275/2fb1ceb8-2926-4408-8a95-ee615d6f64b3)
)

2024-06-01 03:20 UTC, merged