Feature/prototype active teacher metrics
code-dot-org/analytics pull request #114
Opened 2024-05-10 21:31 UTC by bakerfranke

# Description

Please include a summary of the change, including any relevant background, motivation, and context.

If relevant, include a description, screenshots, etc. of new behavior/model/update/...

## Links

Jira ticket(s): []()

## Testing story

- [ ] Does your change include appropriate tests on key columns?
      eg.
      - `not_null`
      - `unique`
      - `dbt_utils.unique_combination_of_columns: , ["value","value","value"...]

**Note: when submitting a new model for review please make sure the following have been tested:**

1. The model compiles (`dbt build -m 'your_model'`)
         or: _has the dbt Cloud job succeeded?_
3. The model runs (`dbt run -m 'your_model'`)
4. The model produces accessible data in the DW (`select 1 from 'your_model'`)

## Privacy

- [ ] 1.	Does this change involve the collection, use, or sharing of new Personal Data?
- [ ] 2.    Do these data exist in the appropriate schema(s)? 
- [ ] 3.	Does this change involve a new or changed use or sharing of existing Personal Data?
- [ ] 4.    Consider: will this data be visible on Tableau? will this data be surfaced in a report exported from Trevor?
- [ ] 5.    If yes to any of the above, please list the models, columns, and justification below:
      i.
      ii.
      iii. 

## PR Checklist:
**Note: if these are not all checked, the PR will be sent back.**

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code adheres to [style guide](https://docs.getdbt.com/best-practices/how-we-style/0-how-we-style-our-dbt-projects)👀 and is **[DRY](https://docs.getdbt.com/terms/dry)**
- [ ] Code is well-commented (**please do not leave extraneous commentary in model code, if it is for the purpose of documentation, please relocate accordingly)
- [ ] Appropriate documentation has been provided (see `.yml.`, did `dbt docs generate` succeed?)
- [ ] New features are translatable or updates will not break up/downstream models
- [ ] Relevant documentation has been added or updated (i.e. `dbt docs` has been updated successfully on [Github Pages](code-dot-org.github.io/analytics/)
- [ ] Pull Request is labeled appropriately (eg. `chore/`, `feature/`, `fix/`)
- [ ] Follow-up work items (including potential tech debt) are tracked and linked (if applicable)

2024-05-14 21:11 UTC, jordan-springer requested changes
let's connect tomorrow if possible and go thru some of this, it's really
close!

2024-05-14 21:11 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_active_teacher.sql
> +        si.sign_in_at::date as sign_in_day,
it may even be more prudent here to use `date_trunc()` or `extract()` even

2024-05-14 21:11 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_active_teacher.sql
> +    where sign_in_at >= '2023-07-01' and u.user_type = 'teacher'
is this filter simply to all the relevant data we need from amplitude? if so, we could apply this at the staging layer or above to reduce overhead.

2024-05-14 21:11 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_active_teacher.sql
> +event_short_names as (
this does not make sense to me. you already have the event names (otherwise you couldn't perform the join)? this is a lot of work for a small move.

2024-05-14 21:11 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_active_teacher.sql
> +        'Change unit'
if you're going to go this route, the expectation is this data is stored as other data ought to be eg. `change_unit` so as to avoid common join errors. also, case you should be consistent.

2024-05-14 21:11 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_active_teacher.sql
> +        a.event_time::date as amp_event_day,
this is not the day, it is the _date_. do you need to extract just the day name?

2024-05-14 21:11 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_active_teacher.sql
> +        ltrim(a.cdo_user_id::varchar, 0) as amp_cdo_user_id, -- Amplitude adds leading zeros to user_ids less than 5 chars long, strip them. (good find by natalia)
move to staging layer

2024-05-14 21:11 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_active_teacher.sql
> +    where event_time > '2023-12-31'
same as previous instance

2024-05-14 21:11 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_active_teacher.sql
> +        end as merged_user_id_source,
if this should never occur, then we can `test` for it rather than do all this

2024-05-14 21:11 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_active_teacher.sql
> +    full outer join
this is where you lose me. can we pair on this quick tomorrow?

2024-05-16 17:40 UTC, bakerfranke commented on dbt/models/marts/teachers/dim_active_teacher.sql
> +        si.sign_in_at::date as sign_in_day,
I want the full calendar date, just as a `date` rather than a timestamp.  I could use date_trunc() first but that returns a timestamp, so I would still need to cast it as a ::date.  I could imagine using date_trunc to make it more explicit to the reader what's going on, but I'll pass here for now.

2024-05-16 19:19 UTC, bakerfranke reviewed
Resolved most issues.  left a few lingering comments.

2024-05-16 19:19 UTC, bakerfranke commented on dbt/models/marts/teachers/_teachers__models.yml
done. made a good catch here. see tests in new commit.

2024-05-16 19:19 UTC, bakerfranke commented on dbt/models/marts/teachers/dim_active_teacher.sql
> +event_short_names as (
good call. moved to rename in staging table rather than here.

2024-05-16 19:19 UTC, bakerfranke commented on dbt/models/marts/teachers/dim_active_teacher.sql
> +    full outer join
To discuss later.  Open issue.

2024-05-16 19:19 UTC, bakerfranke commented on dbt/models/staging/amplitude/_amplitude__models.yml
> +      description: The name of the event as listed in Amplitude.  These have names like "Unit Overview Page Visited By Teacher"
I added not_null tests to a few key fields.

2024-05-16 19:42 UTC, bakerfranke commented on dbt/models/marts/teachers/dim_active_teachers.sql
> +    --inner join event_short_names as e on a.event_type = e.event_type
```suggestion

```

2024-05-23 18:56 UTC, bakerfranke commented on dbt/models/marts/teachers/dim_active_teacher.sql
> +    full outer join
Addressed in most recent commit.  Refactored to no longer use outer join

2024-06-28 16:49 UTC, jordan-springer approved these changes
left some comments but nothing needed right now

2024-06-28 16:49 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_active_teachers.sql
> +-- choice: for now I'm excluding known student users from the model entirely even though the prototype included them
not sure I understand this logic, something to keep an eye on

2024-06-28 16:49 UTC, jordan-springer commented on dbt/models/staging/amplitude/stg_amplitude__active_teacher_events.sql
> +            when event_type = 'Teacher Viewing Student Work' then 'View Work'
wrap in `lower()` to avoid CASE mismatch, such as...
```suggestion
            when lower(event_type) = 'teacher viewing student work' then 'View Work'
```

2024-06-28 16:49 UTC, jordan-springer commented on dbt/models/staging/amplitude/stg_amplitude__active_teacher_events.sql
> +        data,
look out for PII; best practice is to extract the fields you need from the blob and not bring the whole thing in.

2024-06-28 16:49 UTC, merged