Adding school_id to dim models
code-dot-org/analytics pull request #116
Opened 2024-05-14 00:10 UTC by jordan-springer

# Description

Please include a summary of the change, including any relevant background, motivation, and context.

If relevant, include a description, screenshots, etc. of new behavior/model/update/...

## Links

Jira ticket(s): []()

## Testing story

- [ ] Does your change include appropriate tests on key columns?
      eg.
      - `not_null`
      - `unique`
      - `dbt_utils.unique_combination_of_columns: , ["value","value","value"...]

**Note: when submitting a new model for review please make sure the following have been tested:**

1. The model compiles (`dbt build -m 'your_model'`)
         or: _has the dbt Cloud job succeeded?_
3. The model runs (`dbt run -m 'your_model'`)
4. The model produces accessible data in the DW (`select 1 from 'your_model'`)

## Privacy

- [ ] 1.	Does this change involve the collection, use, or sharing of new Personal Data?
- [ ] 2.    Do these data exist in the appropriate schema(s)? 
- [ ] 3.	Does this change involve a new or changed use or sharing of existing Personal Data?
- [ ] 4.    Consider: will this data be visible on Tableau? will this data be surfaced in a report exported from Trevor?
- [ ] 5.    If yes to any of the above, please list the models, columns, and justification below:
      i.
      ii.
      iii. 

## PR Checklist:
**Note: if these are not all checked, the PR will be sent back.**

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code adheres to [style guide](https://docs.getdbt.com/best-practices/how-we-style/0-how-we-style-our-dbt-projects)👀 and is **[DRY](https://docs.getdbt.com/terms/dry)**
- [ ] Code is well-commented (**please do not leave extraneous commentary in model code, if it is for the purpose of documentation, please relocate accordingly)
- [ ] Appropriate documentation has been provided (see `.yml.`, did `dbt docs generate` succeed?)
- [ ] New features are translatable or updates will not break up/downstream models
- [ ] Relevant documentation has been added or updated (i.e. `dbt docs` has been updated successfully on [Github Pages](code-dot-org.github.io/analytics/)
- [ ] Pull Request is labeled appropriately (eg. `chore/`, `feature/`, `fix/`)
- [ ] Follow-up work items (including potential tech debt) are tracked and linked (if applicable)

2024-05-16 20:52 UTC, bakerfranke requested changes
A few suggested changes + one biggish policy issue that this surfaces probably warranting further discussion.

2024-05-16 20:52 UTC, bakerfranke commented on dbt/models/intermediate/int_section_mapping.sql
It needs to be made much more explicitly clear that this model is filtering out all but one student-section mappings.

In the case where a student belongs to multiple sections within a school year (about 5% of students, see data point below), this model is choosing the one the student was added to FIRST within that school_year.  I can understand that as a choice because it won't change later on. But this is a choice that needs to be made explicit and probably discussed further.  

I could see a rationale, for example, that we should choose the section the student was added to most recently within the school year - that might change over time which could add confusion, but it also might be a more accurate representation of what that student is doing....or some other more sophisticated criteria.

@coryamanda -- This is a long standing issue that we should probably review and double-check as a team.  There often comes a point where we just have to choose a section for a student and roll with it, but when we do that it should be made much more explicit when and where that is happening.

To wit - I might suggest renaming this model to something like `int_single_section_student_mapping`.
And updating the .yml documentation explaining all this and the rationale for the choice.

This choice has downstream effects on which school(s) are associated with a student.

2024-05-16 20:52 UTC, bakerfranke commented on dbt/models/intermediate/int_section_mapping.sql
As a data point - we know that ~95% of all student users belong to only 1 section per school year (with the remainder ~4% with 2 sections and <1% with 3 or more sections)  So at face, it might seem okay to pick just one section this way.  And big picture it probably doesn't alter metrics too much. But I think it warrants doing a deeper analysis of the 5% of users who have 2 or more sections to make sure we're making a smart choice, or to understand what we're filtering out.  

For example - of the 5% of users with 2+ sections.... 
* are these users more likely to be older or younger students? 
* how many are dummy accounts?  
* How many actually have the same teacher (and there for de-risking the section choice in terms of school association)?
* How many actually have different teachers with different school associations?
* How many are actually _teachers_?!?!? (the 'student_user_id' in the followers table is a misnomer.  it really means the _user-id-of-the-section-follower_.  Teachers can belong to sections of other teachers.)
* etc.

Answers to these questions might allow us to make a better choice ultimately for which school to associate with a student.

2024-05-16 20:52 UTC, bakerfranke commented on dbt/models/marts/students/_students__models.yml
Can you add tests for unique combinations of columns to the dim_students model?  reviewing this made me realize it would be useful to establish assumptions about the grain here.  For example your model here assumes that student | school_id is a unique combo, and that's not necessarily obvious knowing the nature of the data.

2024-05-17 15:33 UTC, coryamanda commented on dbt/models/intermediate/int_section_mapping.sql
I concur with documenting the fact that it's a single mapping of section to student, whether it's first or most recent, and why we made that choice.

2024-05-17 17:12 UTC, coryamanda commented on dbt/models/marts/students/dim_students.sql
> +        sm.school_id,
NZM: Incorporating section mappings is unnecessary here - simply looking for a lookup that adds school_id where school_info previously existed in the table

2024-05-17 17:15 UTC, coryamanda commented on dbt/models/marts/students/dim_students.sql
> +        sm.school_id,
Broader - do we need to revisit the dim_students table and int_section_mapping to show most recent as opposed to first combination of teacher and school year?

2024-05-17 18:59 UTC, jordan-springer commented on dbt/models/intermediate/int_section_mapping.sql
i'll make a follow-up ticket for this analysis

2024-05-18 02:54 UTC, jordan-springer commented on dbt/models/marts/students/dim_students.sql
> +        sm.school_id,
@cory confirming re: your comment on the JIRA ticket that we no longer need this update to `dim_students`

2024-05-22 20:01 UTC, jordan-springer commented on dbt/models/marts/students/_students__models.yml
i don't see any duplicates for `student_id` | `school_id`

2024-06-01 03:19 UTC, merged