Feature/dim course util
code-dot-org/analytics pull request #127
Opened 2024-06-18 02:30 UTC by jordan-springer

# Description

dim_student_activity captures all student activity at the grain of student_id/level_id/script_id/activity_date. It adds some additional information on the associated course, section (if applicable), teacher, school, and district and some fields to make common aggregations simpler (e.g. month, SY quarter, etc). 

One small note-- this uses the new fields in int_section_mapping to require the student's activity to take place _after_
 they were added to the section and _before_ they were removed (or the end of the school year if not removed). This change may change the counts slightly when verifying against existing dashboards. 

- UPDATE: decided to keep logic same as in other models and count "in a section" by school year, not the added_at date

dim_course_utilization was the version jordan was working on- I've moved it to the archive folder so as not to mess with it. 

## Links

Jira ticket(s): [dataops-872](https://codedotorg.atlassian.net/jira/software/projects/DATAOPS/boards/72/backlog?assignee=631ee7e61f3f6665a603964a&selectedIssue=DATAOPS-872)

You can check the priorities in the [data product spec](https://docs.google.com/document/d/1IxvjZGtXDUxsDn_grKfFslvlCR5M9VNrIWT-SHPdQpk/edit#bookmark=id.qdzufzoum2bi) to test whether each are met with this model. The ones with a check mark should be met by this model, the ones without will be met by a separate model (e.g. projects). 

## Testing story

Generally, we can use [the course utilization dashboard](https://us-east-1.online.tableau.com/#/site/codeorg/views/CourseUtilization/CourseUtilizationbyScriptStageLevel?:iid=2) to verify different counts/ aggregations. I have not yet tested the model against this dashboard- want to verify columns/format before doing so.

2024-08-08 14:51 UTC, nataliazm99 requested changes
Is the date logic for student activity proposed here (that activity only applies to a section after the date the student is added to the section) applying to other models, such as `dim_teacher_status`, `dim_school_status`, `dim_user_course_activity`? The logic should be consistent across models. I also worry that because historically we have assigned activity to the school year, and not only after the date the student joined, overall activity would decrease for past years too.

2024-08-08 14:51 UTC, nataliazm99 commented on archive/dim_course_utilization.sql
> +        cs.course_name,
```suggestion
        cs.course_name,
        cs.unit as unit_name,
        cs.script_id,
        cs.script_name,
        cs.stage_id,
        cs.stage_name, 
        cs.stage_number,
        cs.level_id,
        cs.level_name,
        cs.level_number,
         cs.level_type 
```

2024-08-08 14:51 UTC, nataliazm99 commented on archive/dim_course_utilization.sql
> +        cs.course_name,
Reordering fields and adding some others that are useful for linking and understanding progress/activity type

2024-08-08 14:51 UTC, nataliazm99 commented on archive/dim_course_utilization.sql
> +        cs.script_name,
```suggestion
```

2024-08-08 14:51 UTC, nataliazm99 commented on archive/dim_course_utilization.sql
> +        cs.level_name,
```suggestion
```

2024-08-08 14:51 UTC, nataliazm99 commented on archive/dim_course_utilization.sql
> +        cs.stage_name,
```suggestion
```

2024-08-08 14:51 UTC, nataliazm99 commented on archive/dim_course_utilization.sql
> +        cs.unit                                     as unit_name,
```suggestion
```

2024-08-08 14:51 UTC, nataliazm99 commented on dbt/models/marts/students/dim_student_activity.sql
> +    , cs.script_name_long                                           as script_name
```suggestion
    , cs.script_name                       as script_name
    , cs.unit
```
In `course_structure` script_name_long and script_name_short are fields that were manually updated through the previous year, but we shouldn't use them anymore. Unit is the equivalent,  and it is parsed from the script name

2024-08-08 14:51 UTC, nataliazm99 commented on dbt/models/marts/students/dim_student_activity.sql
> +limit 100
I imagine this will be removed for merging?

2024-08-08 14:51 UTC, nataliazm99 commented on dbt/models/marts/students/dim_student_activity.sql
> +    , sum(time_spent)                                               as minutes_spent
```suggestion
    , sum(time_spent)                                               as time_spent_minutes
```

2024-08-08 14:51 UTC, nataliazm99 commented on dbt/models/staging/dashboard_pii/stg_dashboard_pii__projects.sql
> +        value, -- what do we need this for?
This field has the projects' properties. We use data in here occasionally for attributes of specific projects, and mostly to identify ghost projects (projects started but with no activity):
 `JSON_EXTRACT_PATH_TEXT(sa.value, 'id') <> ''`

2024-08-08 23:29 UTC, allison-code-dot-org commented on archive/dim_course_utilization.sql
> +        cs.course_name,
sorry, this is the archived model jordan was working on!

2024-08-08 23:29 UTC, allison-code-dot-org commented on archive/dim_course_utilization.sql
> +        cs.script_name,
archived model!

2024-08-08 23:29 UTC, allison-code-dot-org commented on archive/dim_course_utilization.sql
> +        cs.level_name,
archived model!

2024-08-08 23:30 UTC, allison-code-dot-org commented on archive/dim_course_utilization.sql
> +        cs.stage_name,
archived model

2024-08-14 19:39 UTC, nataliazm99 approved these changes
Looks good to me!!

2024-08-14 20:32 UTC, merged