build core models
code-dot-org/analytics pull request #171
Opened 2024-08-30 21:38 UTC by allison-code-dot-org

# Description

This PR does two things:
1. Builds dim_global_trained_teacher_script_activity.sql : this is the replacement model to international_student_activity that we previously maintained for the global team. 
2. Makes edits to dim_global_teacher_roster.sql: needed some added fields after discussions with Martina

To do: 
- validation against existing views 
- documentation + data_tests

## Links

Jira ticket(s): [DATAOPS-940](https://codedotorg.atlassian.net/jira/software/projects/DATAOPS/boards/72/backlog?selectedIssue=DATAOPS-940)

2024-09-05 11:52 UTC, jordan-springer requested changes
some changes needed

2024-09-05 11:52 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_global_trained_teacher_script_progress.sql
> +        , max(sa.num_levels_attempted)                          as highest_level_attempted
this is just going to take the biggest number of levels attempted, not necessarily the highest_level. for example, this teacher may have 15 levels attemped of various levels, and here you would report that 15 was the highest level achieved

2024-09-05 11:52 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_global_trained_teacher_script_progress.sql
> +        on tt.teacher_id = sa.section_teacher_id
there are many students per teacher, so this should be a left join

2024-09-11 20:44 UTC, allison-code-dot-org commented on dbt/models/marts/teachers/dim_global_trained_teacher_script_progress.sql
> +        on tt.teacher_id = sa.section_teacher_id
we only want to pull in teachers who have students associated with them in student_activity. A left join would pull in the teachers in trained_teachers who have no student associations in student_activity.

2024-09-11 20:57 UTC, allison-code-dot-org commented on dbt/models/marts/teachers/dim_global_trained_teacher_script_progress.sql
> +        , max(sa.num_levels_attempted)                          as highest_level_attempted
yes, we want the biggest number of levels attempted due to how different scripts are set up. I believe in most cases they will be the same number since previous levels are required to have been attempted before you attempt another. So, a student can only get to level 15 if they've attempted 14 other levels. But in cases where a student only attempts level 15 (and previous levels are not required), I think we want to count that as 1 level attempted. Maybe I'll change the name to most_levels_attempted to be less confusing. @nataliazm99 You have more context on how the curriculum works here- this is how we have reported this metric to international in the past, but open to changing the name or logic if needed. What do you think?

2024-09-12 17:02 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_global_trained_teacher_script_progress.sql
> +        , max(sa.num_levels_attempted)                          as highest_level_attempted
I would check with international what is what they need, because if they mean to understand which level is the highest students' have done, it would be better to use `dim_course_structure.level_number`. If what they need is instead the count of levels then this logic is right, but I would change the description to be aligned with the metric. As far as I know, to do a level there is no requirement to do previous levels, and in CSF some levels have the option to be skipped (these would have best result = -100).

2024-09-18 13:41 UTC, merged