Feature/fct monthly active students
code-dot-org/analytics pull request #181
Opened 2024-09-18 19:09 UTC by jordan-springer

# Description

Please include a summary of the change, including any relevant background, motivation, and context.

If relevant, include a description, screenshots, etc. of new behavior/model/update/...

## Links

Jira ticket(s): []()

## Testing story

- [ ] Does your change include appropriate tests on key columns?
      eg.
      - `not_null`
      - `unique`
      - `dbt_utils.unique_combination_of_columns: , ["value","value","value"...]

**Note: when submitting a new model for review please make sure the following have been tested:**

1. The model compiles (`dbt build -m 'your_model'`)
         or: _has the dbt Cloud job succeeded?_
3. The model runs (`dbt run -m 'your_model'`)
4. The model produces accessible data in the DW (`select 1 from 'your_model'`)

## Privacy

- [ ] 1.	Does this change involve the collection, use, or sharing of new Personal Data?
- [ ] 2.    Do these data exist in the appropriate schema(s)? 
- [ ] 3.	Does this change involve a new or changed use or sharing of existing Personal Data?
- [ ] 4.    Consider: will this data be visible on Tableau? will this data be surfaced in a report exported from Trevor?
- [ ] 5.    If yes to any of the above, please list the models, columns, and justification below:
      i.
      ii.
      iii. 

## PR Checklist:
--> **Note: if these are not all checked, the PR will be sent back.**

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code adheres to [style guide](https://docs.getdbt.com/best-practices/how-we-style/0-how-we-style-our-dbt-projects)👀 and is **[DRY](https://docs.getdbt.com/terms/dry)**
- [ ] Code is well-commented (**please do not leave extraneous commentary in model code, if it is for the purpose of documentation, please relocate accordingly)
- [ ] Appropriate documentation has been provided (see `.yml.`, did `dbt docs generate` succeed?)
- [ ] New features are translatable or updates will not break up/downstream models
- [ ] Relevant documentation has been added or updated (i.e. `dbt docs` has been updated successfully on [Github Pages](code-dot-org.github.io/analytics/)
- [ ] Pull Request is labeled appropriately (eg. `chore/`, `feature/`, `fix/`)
- [ ] Follow-up work items (including potential tech debt) are tracked and linked (if applicable)

2024-09-24 17:46 UTC, allison-code-dot-org requested changes
Overall, I'm on-board with the logic behind defining an "active student", and should be relatively easy to integrate the anonymous/ signed-out usage once we have it. I left one main comment on considerations of the model's grain level and some other smaller notes to consider. Thank you for all your work on this!

2024-09-24 17:52 UTC, jordan-springer commented on dbt/macros/get_cutoff_date.sql
> +    '2019-06-30'  -- You can replace this with a dynamic value, e.g., a variable or config
I'm this used as the standard for our `/marts` offering going forward

2024-09-24 17:53 UTC, jordan-springer commented on dbt/macros/get_cutoff_date.sql
> +    '2019-06-30'  -- You can replace this with a dynamic value, e.g., a variable or config
re-writing to be last of of school_year - 5 would be more optimal for sure, we should do that

2024-09-25 03:23 UTC, jordan-springer commented on dbt/models/marts/students/dim_student_projects.sql
> +        , case when u.user_id   is not null then 1 else 0 end   as is_signed_in
yes -- there are 3 rows, all without a user_id
```
select *
from dbt_jordan.dim_student_projects
where is_signed_in <> known_cdo_user
```

2024-09-25 03:52 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_active_students_monthly.sql
> +        activity_month,
i agree, i am also going to make a yearly model of the same for that purpose.

2024-09-25 14:22 UTC, coryamanda commented on dbt/models/marts/metrics/fct_active_students_monthly.sql
> +        activity_month,
I think Allison makes a good point here. The most common granularity is  for monthly roll-ups, but there are going to be times when we need to adjust that - I'm 100% certain that we will get asked for the same breakouts by week, for different countries, for different age ranges, etc. The problem with dropping the user/day model is that we have no flexibility to meet those asks. For instance, the 2030 goals include breakouts for URG and gender, as well as for curriculum target area. While this approach avoids a large dim_active_students model, we'd end up having to create separate fct aggregates for every breakout or subset of this data we might need. Having a table at the active user/day model that we can aggregate as needed meets a much broader set of needs.

2024-09-25 15:43 UTC, coryamanda commented on dbt/models/marts/metrics/fct_active_students_monthly.sql
> +        activity_month,
@jordan-springer see here

2024-09-26 01:57 UTC, jordan-springer commented
runtime for new `dim_active_students` ~44 min

![image](https://github.com/user-attachments/assets/0705d441-c44b-42d5-8fcb-2a0ec0a6b6a5)

2024-09-26 03:45 UTC, coryamanda commented on dbt/macros/get_cutoff_date.sql
> +    '2019-06-30'  -- You can replace this with a dynamic value, e.g., a variable or config
cool - does it make sense to use this for the cutoff date in dim_active_students as well, or is this only for marts?

2024-09-26 04:13 UTC, jordan-springer commented
checks passed; updated model timing 
![image](https://github.com/user-attachments/assets/8ef8140b-cc86-4950-a42e-96c33c5a2ae1)

2024-09-26 04:16 UTC, jordan-springer commented on dbt/macros/get_cutoff_date.sql
> +    '2019-06-30'  -- You can replace this with a dynamic value, e.g., a variable or config
that's a good question. we can start with dim_active_students and the metrics/ mart and decide what else could be covered?

2024-09-27 22:37 UTC, jordan-springer reviewed
looks good, thanks! we can now also remove this logic from the dim_active_students model

2024-09-27 22:38 UTC, jordan-springer reviewed
👍🏽

2024-09-30 13:43 UTC, coryamanda requested changes

2024-09-30 13:43 UTC, coryamanda commented on dbt/models/marts/students/dim_active_students.sql
> +    where has_sign_in_activity = 1
I think this aggregation is off. When we say 'students must be signed in', that means they can't be anonymous students in the data. This filter is checking to see whether they also have a sign in event on that day. That's not the same thing - a sign in event is an authentication, but we know that many students stay signed in on their browsers for days at a time and that's fine. I think the right filter is cdo_known_user, but you should check that.

2024-09-30 14:09 UTC, coryamanda requested changes

2024-09-30 14:09 UTC, coryamanda commented on dbt/models/marts/students/dim_active_students.sql
> +        and created_date > {{ get_cutoff_date() }}
filter out HOC only usage here. I asked Natalia for her recommended approach here: https://codedotorg.slack.com/archives/C071T8M847J/p1727702582301659

2024-09-30 14:09 UTC, coryamanda commented on dbt/models/marts/students/dim_active_students.sql
> +        and created_date > {{ get_cutoff_date() }}
select distinct course_name
from dev.analytics.dim_course_structure dcs 
where dcs.is_active_student_course = 1

2024-09-30 14:09 UTC, coryamanda commented on dbt/models/marts/students/dim_active_students.sql
> +
Add "where user_id is not null" filter here to remove the anonymous projects. Or use the "known_cdo_user" field you created in dim_student_projects.

2024-09-30 17:30 UTC, coryamanda commented
@jordan-springer A few more updates:
- We need the urg and gender fields added to dim_active_students as we discussed this morning. Just documenting that.
- Remove the filter on course for the user levels join. We can include HOC activity for the overall active students metric

2024-09-30 18:38 UTC, jordan-springer commented on dbt/models/marts/students/dim_active_students.sql
> +        and created_date > {{ get_cutoff_date() }}
removing this

2024-09-30 22:11 UTC, jordan-springer commented
we are also removing sign_in's from active metrics consideration and adding back the `dim_user_course_activity model` .sorry for all the file changes!

2024-10-01 05:22 UTC, coryamanda approved these changes

2024-10-01 05:24 UTC, coryamanda commented
Merging this in without waiting for Allison to re-review, given that her feedback was addressed.

2024-10-01 05:24 UTC, merged