Changes to dim_student_sccript_level_activity to include all activity
code-dot-org/analytics pull request #190
Opened 2024-10-01 22:40 UTC by nataliazm99

Changes to dim_student_sccript_level_activity to include all activity in student-facing content.

# Description
Changes to dim_student_sccript_level_activity to include all activity in student-facing content.

Main changes:
1. Use `student_activity` as base in `final` CTE instead of `sections `which was leaving out unsectioned users
2. Join user information in `final` CTE instead of in `sections` to add this info to all users
3. Add `user_type` to allow filtering for students
4. Add `lesson_id`  for consistency
5. Reorganized fields to make it more user-friendly

## Links

Jira ticket(s): []()

## Testing story

- [ ] Does your change include appropriate tests on key columns?
      eg.
      - `not_null`
      - `unique`
      - `dbt_utils.unique_combination_of_columns: , ["value","value","value"...]

**Note: when submitting a new model for review please make sure the following have been tested:**

1. The model compiles (`dbt build -m 'your_model'`)
         or: _has the dbt Cloud job succeeded?_
6. The model runs (`dbt run -m 'your_model'`)
7. The model produces accessible data in the DW (`select 1 from 'your_model'`)

## Privacy

- [ ] 1.	Does this change involve the collection, use, or sharing of new Personal Data?
- [ ] 2.    Do these data exist in the appropriate schema(s)? 
- [ ] 3.	Does this change involve a new or changed use or sharing of existing Personal Data?
- [ ] 4.    Consider: will this data be visible on Tableau? will this data be surfaced in a report exported from Trevor?
- [ ] 5.    If yes to any of the above, please list the models, columns, and justification below:
      i.
      ii.
      iii. 

## PR Checklist:
--> **Note: if these are not all checked, the PR will be sent back.**

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code adheres to [style guide](https://docs.getdbt.com/best-practices/how-we-style/0-how-we-style-our-dbt-projects)👀 and is **[DRY](https://docs.getdbt.com/terms/dry)**
- [ ] Code is well-commented (**please do not leave extraneous commentary in model code, if it is for the purpose of documentation, please relocate accordingly)
- [ ] Appropriate documentation has been provided (see `.yml.`, did `dbt docs generate` succeed?)
- [ ] New features are translatable or updates will not break up/downstream models
- [ ] Relevant documentation has been added or updated (i.e. `dbt docs` has been updated successfully on [Github Pages](code-dot-org.github.io/analytics/)
- [ ] Pull Request is labeled appropriately (eg. `chore/`, `feature/`, `fix/`)
- [ ] Follow-up work items (including potential tech debt) are tracked and linked (if applicable)

2024-10-01 23:04 UTC, allison-code-dot-org requested changes
Just the small update to filter user_type in CTEs and I think good to go! thank you for digging into this!

2024-10-01 23:04 UTC, allison-code-dot-org commented on dbt/models/marts/students/dim_student_script_level_activity.sql
> +    left join teacher_status as tes  -- left join to avoid missing teachers without status
should keep this as a left join, but shouldn't change results since all teachers have a status in every school year (if never active, they would be market)

2024-10-01 23:04 UTC, allison-code-dot-org commented on dbt/models/marts/students/dim_student_script_level_activity.sql
> +    left join school_status as sst  -- left join to keep sections without an NCES-associated school
ah good call

2024-10-02 12:28 UTC, nataliazm99 commented on dbt/models/marts/students/dim_student_script_level_activity.sql
> +        user_type
I'd rather keep those records and filter them on use than remove them altogether because 1) that is legit activity 2) it is harder to add them back in than to filter them out if they are already in the table. These make up 1.9% of records for SY 2023-24.

2024-10-02 16:16 UTC, coryamanda commented on dbt/models/marts/students/dim_student_script_level_activity.sql
> +        user_type
For posterity: Natalia: "Yes, this is the base for curricular consumption. And it is such a big table that the main use cases are as base to replace the Tableau dashboards that are most used now to track student activity and curriculum use (e.g. course utilization dashboard, student enrollment, etc.) For that purpose it is better to have everything and filter out when needed, otherwise that table can't be used and the logic needs to be recreated if all records are needed"

2024-10-02 16:18 UTC, coryamanda approved these changes

2024-10-02 16:20 UTC, coryamanda commented
Merging without addressing Allison's requested change because, while ideally this would be student-only activity and exclude teachers, making that change now would change the logic on a number of existing deliverables.

2024-10-02 16:20 UTC, merged