Update/2024 Ledgers crosswalk + views for ballmer aggregations
code-dot-org/analytics pull request #197
Opened 2024-10-09 15:31 UTC by coryamanda

# Description

Onboarding the 2024 AP ledger to Hydrone. Next up is the NCES/AI Code crosswalk. I mostly followed Baker's instructions here (Start on p 9): https://docs.google.com/document/d/15QWMs2lM-0ihLZCrZ5UEpzRN4gKjce2W6S-uBUbD6JI/edit

The big thing that I did differently is that I loaded the base data from the College Board much more similarly to how it was provided to me and documented my cleaning steps in the staging table as opposed to doing that outside of dbt. My hope is that this will let us have good documentation about how to clean these and assumptions going forward. 

## Links

Jira ticket(s): []()

## Testing story

- [ ] Does your change include appropriate tests on key columns?
      eg.
      - `not_null`
      - `unique`
      - `dbt_utils.unique_combination_of_columns: , ["value","value","value"...]

**Note: when submitting a new model for review please make sure the following have been tested:**

1. The model compiles (`dbt build -m 'your_model'`)
         or: _has the dbt Cloud job succeeded?_
3. The model runs (`dbt run -m 'your_model'`)
4. The model produces accessible data in the DW (`select 1 from 'your_model'`)

## Privacy

- [ ] 1.	Does this change involve the collection, use, or sharing of new Personal Data? No
- [ ] 2.    Do these data exist in the appropriate schema(s)?  Yes
- [ ] 3.	Does this change involve a new or changed use or sharing of existing Personal Data? No
- [ ] 4.    Consider: will this data be visible on Tableau? will this data be surfaced in a report exported from Trevor? No
- [ ] 5.    If yes to any of the above, please list the models, columns, and justification below:
      i.
      ii.
      iii. 

## PR Checklist:
--> **Note: if these are not all checked, the PR will be sent back.**

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code adheres to [style guide](https://docs.getdbt.com/best-practices/how-we-style/0-how-we-style-our-dbt-projects)👀 and is **[DRY](https://docs.getdbt.com/terms/dry)**
- [ ] Code is well-commented (**please do not leave extraneous commentary in model code, if it is for the purpose of documentation, please relocate accordingly)
- [ ] Appropriate documentation has been provided (see `.yml.`, did `dbt docs generate` succeed?)
- [ ] New features are translatable or updates will not break up/downstream models
- [ ] Relevant documentation has been added or updated (i.e. `dbt docs` has been updated successfully on [Github Pages](code-dot-org.github.io/analytics/)
- [ ] Pull Request is labeled appropriately (eg. `chore/`, `feature/`, `fix/`)
- [ ] Follow-up work items (including potential tech debt) are tracked and linked (if applicable)

2024-10-09 18:03 UTC, allison-code-dot-org requested changes
Left a few comments on code changes- still need to QA the resulting data.

2024-10-09 20:19 UTC, coryamanda commented on dbt/models/staging/external_datasets/_external_datasets__sources.yml
> +      - name: stg_ap_ledgers_raw_2024
I did it to be consistent with previous years in the redshift data, but happy to fix that. Good thought.

2024-10-09 20:29 UTC, coryamanda commented on dbt/models/staging/external_datasets/stg_external_datasets__ap_ledgers_2024.sql
> +            when provider_syllabus = 'Code.org + CMU CS Academy Sample Syllabus' then 'Code.org + CMU CS Academy'
the case used here is consistent with the 2023 data already in analytics.ap_ledgers, which means it's consistent with the code we use to pull what we need from this. If we think this is really meaningful, options would be:
-  lowercase it at the aggregation step, when we union all the different years, and then change the query code
- lowercase it here, as well as in the 2023 load step, and then change the query code

Thoughts?

2024-10-09 20:33 UTC, coryamanda commented on dbt/models/staging/external_datasets/stg_external_datasets__ap_ledgers_2024.sql
> +        case when state in ('AL','AK','AZ','AR','CA','CO','CT','DE','DC','FL',
As a comparison point, in dim_schools, city, state, and school name are all upper case. What would be the reason for doing lower case here?

2024-10-11 14:45 UTC, allison-code-dot-org commented on dbt/models/staging/external_datasets/stg_external_datasets__ap_ledgers_2024.sql
> +        case when state in ('AL','AK','AZ','AR','CA','CO','CT','DE','DC','FL',
I think we should change other models to be all lower case, just so that if these fields are ever used to join, they are consistent with each other and we don't need to worry about/ remember to make the cases the same.

2024-10-11 15:22 UTC, coryamanda commented on dbt/models/staging/external_datasets/stg_external_datasets__ap_ledgers_2024.sql
> +        case when state in ('AL','AK','AZ','AR','CA','CO','CT','DE','DC','FL',
can we table the capitalization discussion to one of the data maintenance work discussions? I don't want to combine this with the existing PR

2024-10-11 15:22 UTC, coryamanda commented on dbt/models/staging/external_datasets/stg_external_datasets__ap_ledgers_2024.sql
> +            when provider_syllabus = 'Code.org + CMU CS Academy Sample Syllabus' then 'Code.org + CMU CS Academy'
tabling capitalization

2024-10-22 20:22 UTC, coryamanda commented on dbt/macros/pad_school_id_zip_etc.sql
> +        when length({{school_id}}) < 8
this is for private schools

2024-10-22 20:29 UTC, coryamanda commented
Additional comments to update:
- heavy_user_students and heavy_user_schools have been reviewed by natalia
- I added two non-required views in the /ballmer folder to support the fuzzy matching on private schools that we do b/c CB doesn't give us a crosswalk for private schools. Those don't feed anywhere and have no downstream effects; they're purely for helping 1) do and then 2) check the matching. Note that in future this could be done with scripting.
-

2024-10-25 16:27 UTC, jordan-springer approved these changes
one comment on some non-us values

2024-10-25 19:28 UTC, merged