Feature/fct monthly active users and accounts created
code-dot-org/analytics pull request #51
Opened 2024-01-15 23:38 UTC by bakerfranke

## Description

This PR establishes two metrics tables that we use in MIR:
* monthly active users -- distinct users who sign in, by month (student/teacher, us/intl)
* monthly accounts created -- distinct accounts created, by month (student/teacher, us/intl)

## Validation

Both tables have been validated against similar results pulling from dashboard production. However there are some differences.

1. One difference is related to another PR (https://github.com/code-dot-org/analytics/pull/50) -- filtering out deleted users at the base_users table creates some differences in results.

2. I can't quite account for some of the differences I'm seeing in sign_ins.  the DBT version has some null fields in the results that are certainly related to the deleted users issue mentioned above, but I can't totally account for some of the other differences.

## Follow-up work

1. Need to finish validating monthly sign ins.  accounts created I'm not worried about.

2. I think there are some nuances to matching dates with school years -- differences between the `date` datatype and `timestamp`.  I'll followup in a different PR

2024-01-16 23:01 UTC, allison-code-dot-org approved these changes
made some formatting/naming changes and added documentation. Otherwise looks good!

2024-01-19 05:09 UTC, jordan-springer requested changes
looks great! few small changes and we're good to go!

2024-01-19 05:09 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_signed_in_users.sql
> +    from {{ ref('base_dashboard__sign_ins') }} -- replace with stg_ eventually?
yes, the reason there isn't one is simply bc i hadn't had use for it. feel free to make that update here or in another pr if you want.

2024-01-19 05:09 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_signed_in_users.sql
> +),
a little trick i learned here from my previous manager, i like to add `where user_id in (select user_id from all_users)`

2024-01-19 05:09 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_accounts_created.sql
> +        case when is_international = 1 then 'intl' else 'us' end        as us_intl,
this is already accounted for here: https://github.com/code-dot-org/analytics/blob/main/dbt/models/staging/dashboard/stg_dashboard__user_geos.sql

2024-01-19 05:09 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_signed_in_users.sql
> +        case when is_international = 1 then 'intl' else 'us' end        as us_intl,
see other model comments

2024-01-19 05:09 UTC, jordan-springer commented on dbt/models/marts/metrics/_metrics__models.yml
> +  - name: fct_monthly_accounts_created
let's make sure to add at least the ootb `tests` here (eg. `not_null`, `unque`)

2024-01-19 05:09 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_signed_in_users.sql
> +        on sign_in_at::date between sy.started_at and sy.ended_at
when you do need to cast like such, it is more performant to pre-process this in the cte

2024-01-21 21:45 UTC, jordan-springer commented on dbt/models/marts/metrics/_metrics__models.yml
> +  - name: fct_monthly_accounts_created
@bakerfranke can we add tests for these new models? start with `not_null` and `unique`, lmk if you want to pair on it

2024-01-21 21:46 UTC, jordan-springer requested changes
@bakerfranke see requested changes

2024-01-22 21:42 UTC, allison-code-dot-org commented on dbt/models/marts/metrics/fct_monthly_accounts_created.sql
> +        case when is_international = 1 then 'intl' else 'us' end        as us_intl,
I think @bakerfranke is creating the word label ('us" or 'intl') to be consistent with our reporting in MIR in the past. Instead of keeping as binary 0/1. Still using the is_international flag

2024-01-23 18:21 UTC, jordan-springer commented on dbt/models/marts/metrics/_metrics__models.yml
> +      - dbt_utils.unique_combination_of_columns:
/
```suggestion
      - dbt_utils.unique_combo-bombo-lol_of_columns:
```

2024-01-28 23:58 UTC, Baker commented on dbt/models/marts/metrics/fct_monthly_accounts_created.sql
> +        on ac.created_at::date between sy.started_at and sy.ended_at
Wrong baker, @bakerfranke . 😂

2024-01-29 20:00 UTC, jordan-springer requested changes
see comments

2024-01-29 20:01 UTC, bakerfranke reviewed
Committing some comments in response to @jordan-springer

2024-01-30 19:31 UTC, jordan-springer requested changes
tests are failing, please review and fix

2024-01-31 16:49 UTC, bakerfranke reviewed
@jordan-springer ready for your final review

2024-01-31 19:25 UTC, jordan-springer reviewed
almost there! few suggestions

2024-01-31 19:25 UTC, jordan-springer commented on dbt/models/marts/metrics/_metrics__models.yml
> +            - iso_week
these seem redundant, do we need three different week fields?

2024-01-31 19:25 UTC, jordan-springer commented on dbt/models/marts/metrics/_metrics__models.yml
> +            - created_at_year
probably don't need both years here right?

2024-01-31 19:25 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_accounts_created.sql
> +    from {{ref('stg_dashboard__users')}}
do you want to update these two to use `dim_users` instead?

2024-01-31 19:25 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_signed_in_users.sql
> +        case when u.user_type is null then '' else u.user_type end      as user_type,
I thought we were going to move this logic upstream?

2024-01-31 19:25 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_signed_in_users.sql
> +        date_part(year, si.sign_in_at)::integer                         as sign_in_year,
extract I think is better here but I can't remember why...

2024-01-31 19:25 UTC, jordan-springer commented on dbt/models/staging/dashboard/_dashboard__models.yml
> +    tests:
```suggestion
    tests:
        - not_null
        - unique
    
```

2024-01-31 19:25 UTC, jordan-springer commented on dbt/models/staging/dashboard/_dashboard__models.yml
> +      - dbt_utils.unique_combination_of_columns:
this isn't needed when only using 1 column

2024-01-31 19:25 UTC, jordan-springer commented on dbt/models/staging/dashboard/_dashboard__models.yml
> +      - name: user_id
repeat

2024-01-31 20:28 UTC, jordan-springer approved these changes
g2g

2024-01-31 20:51 UTC, merged