Feature/fct school acquisition metrics
code-dot-org/analytics pull request #52
Opened 2024-01-16 00:08 UTC by bakerfranke

## Description
This PR is a second pass at defining a Wheatley school acquisition metrics table.

A major contribution to this PR is the definition of a new intermediate table called `int_school_weeks`.  The attempt here is to solve the problem of how to align school year weeks with standard ISO weeks and this table propose a solution. 

Please read the comments in the code, and the methodology of `int_school_weeks` carefully because it will define how we define weeks of the school year moving forward. Its design is an attempt to mimic `int_school_years` in terms of how analysts or modelers would join to it, and also to not conflict with what have become our standard school year boundaries.

I think that is a good solution moving forward, and better than what we currently use in terms of standardizing school weeks. It will mean validation might get tricky because some schools might shift from one schoolyard to another based on how we currently do reporting, but I think those differences well in the end be marginal and it's worth this change to standardize the way we segment data by weeks of the school year.

**THIS PR IS LARGELY ABOUT APPROVING `int_school_weeks` and merging it into main. 

The weekly school acquisition metrics code, was updated to incorporate this new table, but follow up work is to validate.

## Followup work

* validate School acquisition metrics against current reporting

2024-01-16 17:40 UTC, allison-code-dot-org approved these changes
made some minor formatting changes and added tests/documentation. Although the code looks convoluted, I can see how it runs faster than the alternative approach mapped out. Tested the build and verified the table for a few school years- all looks good!

2024-01-16 17:40 UTC, allison-code-dot-org commented on dbt/models/intermediate/int_school_weeks.sql
> +{# NOTES:
can you add the user-facing part of this documentation to the intermediate models .yml file?

2024-01-16 17:40 UTC, allison-code-dot-org commented on dbt/models/intermediate/int_school_weeks.sql
> +-- This JINJA worked to generate all the days I think but was really slow.  Defered to composing in CTEs below with unions, joins, and multiplication
just a note to (eventually) delete this part for cleanliness, but good context for now

2024-01-16 18:06 UTC, bakerfranke commented on dbt/models/intermediate/int_school_weeks.sql
> +{# NOTES:
Ah, yes.  Thanks for pointing this out.

2024-01-16 18:08 UTC, bakerfranke commented on dbt/models/intermediate/int_school_weeks.sql
> +-- This JINJA worked to generate all the days I think but was really slow.  Defered to composing in CTEs below with unions, joins, and multiplication
roger.

2024-01-16 22:23 UTC, allison-code-dot-org commented on dbt/models/marts/metrics/fct_weekly_school_acquisition_metrics.sql
>          start_week,
small thing, but do you think we should label this "iso_week" (or even consider not including it) to better differentiate with school_year_week?

2024-01-17 18:27 UTC, jordan-springer commented on dbt/models/intermediate/int_school_weeks.sql
> +    (ended_at - started_at) + 1 as days_interval
```suggestion
    datediff('day',started_at,ended_at) as days_interval
```

2024-01-17 18:29 UTC, jordan-springer commented on dbt/models/intermediate/int_school_weeks.sql
> +order by started_at
this looks good. I think this should be a table that is loaded once a year via a `seed` file instead of all this computation occuring everytime we run our jobs

2024-01-17 20:01 UTC, allison-code-dot-org approved these changes
niiiice

2024-01-19 16:04 UTC, jordan-springer requested changes
the `school_level_simple` logic is redundant here, let's remove and go back to the `bit` fields we are pre-processing for you in the base/staging layers and providing in `dim_schools`

2024-01-19 16:04 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_weekly_school_acquisition_metrics.sql
> +        school_year_week,
please reconsider the fields below like `el_schools`. you are creating a column `school_level_simple` which is a concat of all the possible values, then you are fuzzy parsing it to get back to where it is el,mi,hi (which the original columnd already provide for you). less is more, if you're doing this much transformation in a dim/fct model, something upstream needs to be updated. 💡

2024-01-21 21:43 UTC, merged