fix/left pad all school ids
code-dot-org/analytics pull request #62
Opened 2024-01-22 16:13 UTC by bakerfranke

## Description

This PR introduces a macro for left-padding school ids with 0s where needed.

school_id as a field comes in from source data in several different places so to solve with SQL at the staging level would require copy/pasting logic for the padding.  Instead we put the logic in a single macro and call it from places where school_id is coming in.

## Future work
We should probably put some kind of test in to ensure that all NCES ids being used in the system are 8 or 12 characters.  I'm a little nervous that we may unwittingly onboard data from source in the future where we'll forget to apply this macro.  It should fail to build noisily if so.

2024-01-22 21:35 UTC, allison-code-dot-org reviewed
This seems good as a solution- I'm only wondering why we chose to not do this before. I can't remember the exact reasons, but I remember @nataliazm99 and @jordan-springer and I deciding against it? Maybe Natalia will have more context here.

2024-01-24 18:45 UTC, jordan-springer requested changes
Looks good, few changes and follow-up

2024-01-25 21:01 UTC, bakerfranke commented on dbt/macros/pad_school_id.sql
> +        when length({{ school_id }}) = 11 then lpad({{ school_id }}, 12, '0')
school_id length can either be 8 or 12.  Agree we should add a test.  the real risk comes in when onboarding NCES data each year.  If we can correct it coming in the door - that's where the test should be.

2024-01-25 21:03 UTC, bakerfranke commented on dbt/models/staging/dashboard/stg_dashboard__school_infos.sql
> +        school_info_id,
tl;dr - school_info_id is an id our application gives to a school-as-entered-by-a-teacher.  If that school matches/can be found in the NCES set of schools a `school_id` is associated with it as well.  Not all schools are US/NCES schools so this is our system for capturing them.

2024-01-25 21:07 UTC, bakerfranke commented on dbt/models/staging/dashboard/base/base_dashboard__sections.sql
> +        deleted_at
noted. done.

2024-01-25 21:55 UTC, bakerfranke commented
@jordan-springer @allison-code-dot-org 

I updated and renamed this PR to match the branch I was working on (I had sent PR for just the school_id padding macro.  But now this is the major PR to complete the validation of school acquisition metrics).

I've significantly updated the front page/description.  I'm a bit at a loss for tests.  I put a put a few testing cases in the doc but it might be trivial.  

But I think this is ready for review.

**NOTE**
My preference is that if there is non-functional work (like fixing/adding documentation, styling nits, etc) that it be turned into jira tickets for fast-follow cleanup work.  **We need this merged so that we can continue making correct data/dashboards collateral for the launch**

2024-01-29 16:47 UTC, jordan-springer commented on dbt/models/staging/dashboard/stg_dashboard__school_stats_by_years.sql
> +        case
@bakerfranke are both of these necessary? why did we remove the coalesce statement?

2024-01-29 18:47 UTC, jordan-springer approved these changes

2024-01-29 18:47 UTC, jordan-springer commented on dbt/macros/pad_school_id.sql
> +        when length({{ school_id }}) = 11 then lpad({{ school_id }}, 12, '0')
^ I agree, and we should probably address this in the /base model

2024-01-29 18:47 UTC, jordan-springer reviewed
looks good, a few things to update still but I will add in a separate commit

2024-01-29 19:15 UTC, bakerfranke reviewed
@jordan-springer - I responded to your new questions.

2024-01-29 19:15 UTC, bakerfranke commented on dbt/models/staging/dashboard/stg_dashboard__school_stats_by_years.sql
> +        case
Yes, both are necessary.  The data we get from NCES is...messy.  In theory it gives both the low and highest grade served, as well as 0/1 for each grade level.  However, sometimes it doesn't, sometimes it's null, sometimes it's incomplete...and a mix of all those.  

Largely what I'm trying to do here is make hydrone schools match rosetta school stats - which it does.  I used the logic in the existing school stats to identify cases where the prev version of hydrone was missing or misallocating schools.

2024-01-29 19:15 UTC, bakerfranke commented on dbt/models/staging/dashboard/stg_dashboard__school_stats_by_years.sql
> +            when grades_offered_lo is null then null -- I don't this is possible unless everything else is already null
It is probably safe to remove this line.  I kept it in because analysis.school_stats has it...and I was trying to make sure it was consistent.  Everything matches now so i was relucted to remove and re-validate.

2024-01-29 19:15 UTC, bakerfranke commented on dbt/models/staging/dashboard/stg_dashboard__school_stats_by_years.sql
> +        case
The coalesce fails in cases where elementary schools serve some elementary grades but not all because it reports 0/1 as well as null/1 for these fields.  For example if some school serves only grades 1-5, then pk=0 and kg=0.   So all grade levels are: 0,0,1,1,1,1,1

We want to call that an elementary school but if you coalese those values 0 is the first non-null value so it reports it as '0' -- not an elementary school.   Coalese would work if it was: null, null, 1,1,1,1,1, but not all cases are like that. So i replaced it with a big OR.

2024-01-29 19:52 UTC, merged