Feature/sections
code-dot-org/analytics pull request #67
Opened 2024-01-27 00:23 UTC by allison-code-dot-org

**What?**

This PR adds dim_sections which includes all sections ever created. Aside from basic dimensional information about each section (e.g. name, login_type, etc), it adds:
1. a flag for is_active
2. calculations for the number of students added (num_students_added) and 
3. the number of active students if the section is active (num_students_active)

**How would this be used?**

This model is meant to be user-facing in trevor and help answer questions like: 
- how big are active sections in terms of total students added and active students? 
- how many active sections are there for CSF in 22-23? 

**Additional notes**

This model pulls in all the information from int_active_sections for all sections who are active. Thus, we would NOT need to make int_active_sections user facing anymore with the addition of this model.

2024-01-27 18:29 UTC, bakerfranke commented
Overall there's an issue being caused by the fact that we're trying to account for all sections, but we've made the metrics around sections by school year.  The current version of dim_sections effectively excludes all sections that have no followers  (~1M) sections.  That would be fine in many cases but if we're surfacing dim_sections to users then, as a user, I would expect it to include ALL sections ever made.   

Another potential issue is that dim_sections is producing more than one-row per section here because of the metrics stuff mentioned above.  I think we need to make a decision about the grain here. 

given that it's called dim_sections, my expectation that it would be one row per section, NOT one row per section per school year.    I think I would propose making it one row per sections, and aggregating the section metrics to that grain, and including columns for the first school year, last school year and number of years over which the metrics are represented.

[incomplete comment. saving for now to share initial thoughts. will try to propose solution]

2024-01-28 14:44 UTC, bakerfranke requested changes
Overall there is a grain-size decision I think we need to make that might suggest a different table name.  There are a few inline changes I suggest as well.

----

1. In the PR description @allison-code-dot-org wrote that this is a table "which includes all sections ever created."  -- it doesn't.  And it's because int_active_sections drives it, and int_active_sections only includes sections that have followers.  It turns out ~1M sections exist that don't have a single follower.

2. If the goal is to serve out a user-facing version of int_active_sections, then I think we should call this dim_active_sections.  The grain is section_id | school_year, and sections that are re-used YoY will appear in multiple records.

3. However, I do think it would be useful to have some kind of summary of section metics at the one-section_id-per-row level.  That would mean a table based on stg_sections (to actually get ALL section_ids) with a summary of int_active_sections that is aggregated at the section_id level.

note for example: right now `school_year` is coming from `int_active_sections` <-- `int_section_mapping` where the `school_year` is based on the created_at timestamp of the follower record(s) in the section, and the section_id may appear in multiple school years.  If this is supposed to be a summary of each section then I would expect `school_year` to be the school_year the section was created with some columns of aggregate stats about the section: first_school_year, most_recent_school_year, total_years_with_followers...stuff like that.

I think there are use cases for both.  And ultimately, we need to make a decision about the grain here, and make sure we're making that choice intentionally.

Should we do both?

@allison-code-dot-org

2024-01-29 19:59 UTC, jordan-springer requested changes
close, few small changes

2024-01-29 19:59 UTC, jordan-springer commented on dbt/models/marts/sections/dim_sections.sql
> +    from {{ ref('int_active_sections') }}
if we are pulling active sections here, we would do well to filter the other sections CTE with this

2024-01-29 19:59 UTC, jordan-springer commented on dbt/models/staging/dashboard/base/base_dashboard__followers.sql
> +    --where deleted_at is null
moving forward the only comments we want in models are notes that are not otherwise relevant for docs. so this line would just be removed going forward FYI @bakerfranke @allison-code-dot-org

2024-01-29 19:59 UTC, jordan-springer commented on dbt/models/marts/sections/dim_sections.sql
> +    group by 1, 2, 3, 4
```suggestion
{{ dbt_utils.group_by(4) }}
```

2024-01-29 21:03 UTC, allison-code-dot-org commented on dbt/models/staging/dashboard/base/base_dashboard__followers.sql
> +    --where deleted_at is null
yeah forgot to delete

2024-01-30 17:13 UTC, jordan-springer approved these changes

2024-01-30 17:14 UTC, merged