fix/dim_students
code-dot-org/analytics pull request #73
Opened 2024-01-31 19:11 UTC by allison-code-dot-org

added races field back in in base and staging. Once dim_users is merged, should be pulled in on select *.

2024-01-31 19:56 UTC, jordan-springer requested changes
few things

2024-01-31 19:56 UTC, jordan-springer commented on dbt/models/staging/dashboard_pii/stg_dashboard_pii__users.sql
> +            when races like '%hispanic%' then 'hispanic'
is there a list of accepted values for race? if so, we wouldn't need to fuzzy match here. could also use the accepted values test to handle the `else` condition

2024-01-31 19:56 UTC, jordan-springer commented on dbt/models/staging/dashboard_pii/stg_dashboard_pii__users.sql
> +        deleted_at,
why would we want to include purged and/or deleted users in this model?

2024-02-01 12:05 UTC, bakerfranke commented on dbt/models/staging/dashboard_pii/stg_dashboard_pii__users.sql
> +            when races like '%hispanic%' then 'hispanic'
there is a set.  It's 7 or eight possible items, and/but they can be permuted as a comma-separated list in 7! ways.  So fuzzy match is necessary.

2024-02-01 12:08 UTC, bakerfranke commented on dbt/models/staging/dashboard_pii/stg_dashboard_pii__users.sql
> +        deleted_at,
There's some difference between delete and purge.  Of fields in users that we're bringing in there's plausible analytic need for these fields, but I don't think its something we'd be moving in to a user-facing model immediately.

2024-02-01 12:09 UTC, bakerfranke reviewed
Answered some questions from jordan.  Did not thoroughly review after my contribution, but I think it LGTM.

2024-02-01 12:09 UTC, bakerfranke approved these changes

2024-02-01 16:18 UTC, jordan-springer commented
@allison-code-dot-org can we make a decision on which fields to pull from `users_pii` vs `users`? the two models are almost identical atm...

2024-02-01 18:41 UTC, merged