Remove references student_id, teacher_id
code-dot-org/analytics pull request #84
Opened 2024-02-09 20:25 UTC by jordan-springer

# Please follow the instructions below when submitting a pull request:

## For dbt Cloud Pull Request:

If you are trying to test your branch, submit a pull request and dbt Cloud will kick-off a run to validate.
If you are trying to **draft** a pull request, please select "Draft" so as to avoid dbt Cloud kicking-off and unnecessary job.

## Description

Please include a summary of the change, including any relevant background, motivation, and context.

If relevant, include a description, screenshots, etc. of new behavior/model/update/...

## Links

Jira ticket(s): []()

## Testing story

- [ ] Does your change include appropriate tests on key columns?
      eg.
      - `not_null`
      - `unique`
      - `dbt_utils.unique_combination_of_columns: , ["value","value","value"...]

**Note: when submitting a new model for review please make sure the following have been tested:**

1. The model compiles (`dbt build -m 'your_model'`)
         or: _has the dbt Cloud job succeeded?_
3. The model runs (`dbt run -m 'your_model'`)
4. The model produces accessible data in the DW (`select 1 from 'your_model'`)

## Privacy

- [ ] 1.	Does this change involve the collection, use, or sharing of new Personal Data?
- [ ] 2.    Do these data exist in the appropriate schema(s)? 
- [ ] 3.	Does this change involve a new or changed use or sharing of existing Personal Data?
- [ ] 4.    Consider: will this data be visible on Tableau? will this data be surfaced in a report exported from Trevor?
- [ ] 5.    If yes to any of the above, please list the models, columns, and justification below:
      i.
      ii.
      iii. 

## PR Checklist:
--> **Note: if these are not all checked, the PR will be sent back.**

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code adheres to [style guide](https://docs.getdbt.com/best-practices/how-we-style/0-how-we-style-our-dbt-projects)👀 and is **[DRY](https://docs.getdbt.com/terms/dry)**
- [ ] Code is well-commented (**please do not leave extraneous commentary in model code, if it is for the purpose of documentation, please relocate accordingly)
- [ ] Appropriate documentation has been provided (see `.yml.`, did `dbt docs generate` succeed?)
- [ ] New features are translatable or updates will not break up/downstream models
- [ ] Relevant documentation has been added or updated (i.e. `dbt docs` has been updated successfully on [Github Pages](code-dot-org.github.io/analytics/)
- [ ] Pull Request is labeled appropriately (eg. `chore/`, `feature/`, `fix/`)
- [ ] Follow-up work items (including potential tech debt) are tracked and linked (if applicable)

***
updated 2024-01-22 ls
changelog:
auth.      descr.      date
js         init        2024-01-22              
js         v1.2        2024-02-06

2024-02-16 17:51 UTC, nataliazm99 requested changes
I added suggestions and comments to ensure we use definitions consistent with our business processes. Also, I'm noticing changes to remove user_type, and, as we had agreed that it was useful to have both teacher and student activity in the activity tables, we need to have the ability to differentiate by user_type, so we should make sure that field is included in all relevant tables.

2024-02-16 17:51 UTC, nataliazm99 commented on dbt/models/marts/users/dim_user_course_activity.sql
> +        -- u.user_type,
We need the user_type. This table should have both teacher and student activity, and we need to be able to differentiate and filter as their activity is very different. 
```suggestion
       u.user_type,
```

2024-02-16 17:51 UTC, nataliazm99 commented on dbt/models/marts/users/dim_user_course_activity.sql
> +    {{ dbt_utils.group_by(3) }}
Adding back the user_type, the group would be four fields
```suggestion
    {{ dbt_utils.group_by(4) }}
```

2024-02-16 17:51 UTC, nataliazm99 commented on dbt/macros/us_intl_label.sql
Also, `dim_users` and others have the labels in lower case, can we keep them consistent to allow easy joins? preferably lower case

2024-02-16 19:40 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_signed_in_users.sql
> +             else 'unknown' end as us_intl,
on second thought, I'm just going to move this concept down to the staging layer so we don't have to write this everytime.

or use that macro I built..

2024-02-16 19:41 UTC, jordan-springer commented on dbt/models/marts/students/dim_student_status.sql
> +            then 'active - new student'
@bakerfranke @nataliazm99 I updated these status labels, what do we think?

2024-02-16 19:44 UTC, jordan-springer reviewed
ok cleaning this up and will get back to you @nataliazm99

2024-02-17 15:21 UTC, bakerfranke requested changes
First pass review here.  May have more later.

2024-02-17 15:21 UTC, bakerfranke commented on dbt/models/staging/dashboard/stg_dashboard__users.sql
> +        -- nullif(lower(gender),'') as gender,
why are we removing these fields?  These are commonly requested / needed fields for analysis and self-serve.

2024-02-17 15:21 UTC, bakerfranke commented on dbt/models/marts/metrics/fct_monthly_signed_in_users.sql
> +        count(distinct si.user_id)          as total_user_sign_ins
my $0.02 - "total" can lead to misconceptions here because of the segmentation by month and year.  In other words, I think it's a misnomer.  To wit: in some of our other monthly metrics tables we have a field like "running_total".  And we deliberately avoided having both "total" and "running_total" to avoid potential confusion.  I think my larger point is one around consistency.  This nomenclature potentially introduces an inconsistency.

2024-02-20 16:34 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_teacher_status.sql
> +        end as teacher_status
+1 I am hesitant that no longer using the cumulative activity counter (ever_active_before) might lead to wrong results. We need to be 100% sure the results are exactly the same as the vetted version before publishing any results

2024-02-20 19:18 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_teachers.sql
> +            order by si.school_id, usi.ended_at desc) as rnk
do `school_id` change often during a school year? shouldn't the most recent, not null value suffice here?

2024-02-20 21:30 UTC, jordan-springer commented on dbt/models/marts/users/dim_user_course_activity.sql
> +    {{ dbt_utils.group_by(3) }}
won't user_type be 'student' every time @nataliazm99?

2024-02-20 22:02 UTC, jordan-springer commented on dbt/models/staging/dashboard/stg_dashboard__users.sql
> +        -- nullif(lower(gender),'') as gender,
we are pulling them from the other model `stg_dashboard_pii__users`

2024-02-21 03:46 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_teacher_status.sql
> +        end as teacher_status
I understand, I will revert it back.

2024-02-21 03:48 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_signed_in_users.sql
> +        count(distinct si.user_id)          as total_user_sign_ins
kk

2024-02-21 03:50 UTC, jordan-springer commented
thanks all for your helpful reviews, I think I covered everything and just had a run succeed locally. I apologize for writing over some of your earlier work, I was trying to build upon not tear down.

2024-02-21 03:53 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_accounts_created.sql
> -        us_intl,
actually this can go back, I moved the `us_intl` down to the staging layer and it's now avail in`dim_users`

2024-02-21 03:53 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_accounts_created.sql
> +             else 'missing' end as us_intl,
```suggestion
      us_intl,
```

2024-02-21 03:55 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_signed_in_users.sql
> +             else 'unknown' end as us_intl,
moved to staging, access from `dim_users`

2024-02-21 03:56 UTC, jordan-springer commented on dbt/models/marts/metrics/fct_monthly_signed_in_users.sql
> +             else 'unknown' end as us_intl,
```suggestion
        us_intl,
```

2024-02-21 13:49 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_teachers.sql
> +            order by si.school_id, usi.ended_at desc) as rnk
To get the most recent school_id associated with a teacher you would only rank ordering by `usi.ended_at desc`. The school_id is the school's identifier, so when ordering by school_id on a partition by teacher you would get the school with the lowest school_id for that teacher, not necessarily the most recent one. 
So this should be:
```
partition by teachers.user_id 
            order by usi.ended_at desc) as rnk
```

2024-02-21 19:43 UTC, bakerfranke commented on dbt/models/staging/dashboard/stg_dashboard__users.sql
> +        -- nullif(lower(gender),'') as gender,
ah.  makes sense

2024-02-21 19:49 UTC, bakerfranke commented on dbt/models/marts/teachers/dim_teachers.sql
> +            order by si.school_id, usi.ended_at desc) as rnk
I think Natalia is right there.  But I'd want to test it.  in answer to your question @jordan-springer yes the school id can change during a school year.  Whether it's often for a particular teacher or not is irrelevant I think - but it's very common.  So the decision here is: for cases where a teacher has multiple school association records which one should we take?  I think we're saying it should be the "most recent" which would be the one with the max `ended_at` date assuming that we've set the ended_at data for the current school to `9999-12-31` (or something like that).

This gets more complicated if you bring school_years into the mix as a grain, but I think dim_teachers is supposed to just represent the most current up to date teacher state.

2024-02-22 04:49 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_teachers.sql
> +            order by si.school_id, usi.ended_at desc) as rnk
thats what I went with in the most recent commit, thanks all!

2024-02-22 13:23 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_teachers.sql
> +            order by si.school_id, usi.ended_at desc) as rnk
This is still ordering by school_id, it should not do that. It should be:
```
partition by teachers.user_id 
            order by usi.ended_at desc) as rnk
```

2024-02-22 19:15 UTC, bakerfranke requested changes

2024-02-22 19:15 UTC, bakerfranke commented on dbt/models/marts/teachers/dim_teacher_status.sql
> +        end as teacher_status
It looks like this wasn't reverted back?

2024-02-22 19:15 UTC, bakerfranke commented on dbt/models/marts/teachers/dim_teacher_status.sql
> +             then 'active - new teacher'
There still is no case for "reacquired" listed here.

2024-02-23 15:26 UTC, bakerfranke approved these changes
The things that stuck out to me from previous review have been resolved.  I made one comment that I think should be non-blocking on a merge but turned into future work.

2024-02-23 15:26 UTC, bakerfranke commented on dbt/models/marts/teachers/dim_teacher_status.sql
> +        and course_name in ('csa', 'csp', 'csd', 'csf', 'csc', 'ai', 'hoc') -- Without this filter, it is counting as active teachers who are not teaching student-facing courses, or courses that are
The virtual courses are student-facing courses and I've recently discovered some signal that teachers are still teaching them.  I think should be included in the active-teacher group.  It would need to be paired/mirrored in student activity as well.

2024-02-26 15:59 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_teacher_status.sql
> +        and course_name in ('csa', 'csp', 'csd', 'csf', 'csc', 'ai', 'hoc') -- Without this filter, it is counting as active teachers who are not teaching student-facing courses, or courses that are
```suggestion
        and course_name in ('csa', 'csp', 'csd', 'csf', 'csc', 'ai') -- Without this filter, it is counting as active teachers who are not teaching student-facing courses, or courses that are defined as not counting towards our metrics: they might be teaching PD courses, or some old virtual courses. We wouldn't consider as 'active' the teacher or the school of such a teacher if they are not teaching a student-facing course. Once we redesign course_structure we can adjust this filter to something more evergreen.
02/26/24: Removed HOC from the list fo courses to keep it consistent with school status
```

2024-02-28 20:28 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_teacher_status.sql
> +        and course_name in ('csa', 'csp', 'csd', 'csf', 'csc', 'ai', 'hoc') -- Without this filter, it is counting as active teachers who are not teaching student-facing courses, or courses that are
why are you removing HOC?

2024-02-28 21:35 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_teacher_status.sql
> +        and course_name in ('csa', 'csp', 'csd', 'csf', 'csc', 'ai', 'hoc') -- Without this filter, it is counting as active teachers who are not teaching student-facing courses, or courses that are
To keep it consistent with school status, to consider a school active we don't count HOC activity as we aim for more substantive CS teaching and learning.

2024-02-28 23:04 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_teacher_status.sql
> +        and course_name in ('csa', 'csp', 'csd', 'csf', 'csc', 'ai', 'hoc') -- Without this filter, it is counting as active teachers who are not teaching student-facing courses, or courses that are
@nataliazm99 do we want to exclude 'hoc' here also?

2024-02-29 15:32 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_teacher_status.sql
> +        and course_name in ('csa', 'csp', 'csd', 'csf', 'csc', 'ai', 'hoc') -- Without this filter, it is counting as active teachers who are not teaching student-facing courses, or courses that are
Unresolving just so it's visible

2024-02-29 17:42 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_teacher_status.sql
> +        and course_name in ('csa', 'csp', 'csd', 'csf', 'csc', 'ai', 'hoc') -- Without this filter, it is counting as active teachers who are not teaching student-facing courses, or courses that are
```suggestion
        and course_name in ('csa', 'csp', 'csd', 'csf', 'csc', 'ai') -- Without this filter, it is counting as active teachers who are not teaching student-facing courses, or courses that are defined as not counting towards our metrics: they might be teaching PD courses, or some old virtual courses. We wouldn't consider as 'active' the teacher or the school of such a teacher if they are not teaching a student-facing course. Once we redesign course_structure we can adjust this filter to something more evergreen. @nataliazm99 

```

2024-02-29 21:54 UTC, jordan-springer commented on .gitignore
> +/dev/
```suggestion
dev/
```

2024-03-01 22:32 UTC, nataliazm99 requested changes
I reviewed and left some comments. The only question I have is right now `dim_teachers` is only pulling school information for schools that have an NCES match, I believe it would be useful to pull in both `school_id` and `school_info_id` because in cases when it doesn't match an NCES id,  `school_info_id` still allows to match to manually-entered school information, which provides useful data, especially regarding geographic location. Plus, filtering by `school_id` means we might be leaving out more recent school information without an NCES match.
Other than that, and assuming previous changes were addressed, I'm good on merging this.

2024-03-01 22:32 UTC, nataliazm99 commented on dbt/models/marts/teachers/dim_teachers.sql
> +    where school_id is not null
Using school_id will only bring in schools matched to an NCES id. Is this the purpose? What about teachers whose school doesn't match an NCES school, like international schools or any that for any reason can't find a match? Wouldn't it be better to pull both `school_info_id` and `school_id`? Also, filtering by `school_id` here,  if a teacher has a more recent `school_info_id` without a match to an NCES id (`school_id = null`), the one we would be pulling is the older one that has an NCES match.

2024-03-01 22:32 UTC, nataliazm99 commented on dbt/models/marts/users/dim_user_levels.sql
This table would be more helpful joined to course_structure to add the course, unit and descriptions of level and script. Adding the user type would be useful too. That can be tackled in a later release.

2024-03-05 04:11 UTC, jordan-springer commented on dbt/models/marts/teachers/dim_teachers.sql
> +    where school_id is not null
Yes, I believe this was intentional-- at the time, we were of the opinion that there wasn't much value to the `school_info` data and therefore, non-NCES schools were the scope. I agree with your point tho and will make the update, I agree we should not be restrictive here cc @allison-code-dot-org

2024-03-05 04:13 UTC, jordan-springer reviewed
g2g

2024-03-05 04:20 UTC, merged