Feature/dataops 563
code-dot-org/analytics pull request #94
Opened 2024-02-27 20:48 UTC by jordan-springer

# Description

Please include a summary of the change, including any relevant background, motivation, and context.

If relevant, include a description, screenshots, etc. of new behavior/model/update/...

## Links

Jira ticket(s): []()

## Testing story

- [ ] Does your change include appropriate tests on key columns?
      eg.
      - `not_null`
      - `unique`
      - `dbt_utils.unique_combination_of_columns: , ["value","value","value"...]

**Note: when submitting a new model for review please make sure the following have been tested:**

1. The model compiles (`dbt build -m 'your_model'`)
         or: _has the dbt Cloud job succeeded?_
3. The model runs (`dbt run -m 'your_model'`)
4. The model produces accessible data in the DW (`select 1 from 'your_model'`)

## Privacy

- [ ] 1.	Does this change involve the collection, use, or sharing of new Personal Data?
- [ ] 2.    Do these data exist in the appropriate schema(s)? 
- [ ] 3.	Does this change involve a new or changed use or sharing of existing Personal Data?
- [ ] 4.    Consider: will this data be visible on Tableau? will this data be surfaced in a report exported from Trevor?
- [ ] 5.    If yes to any of the above, please list the models, columns, and justification below:
      i.
      ii.
      iii. 

## PR Checklist:
**Note: if these are not all checked, the PR will be sent back.**

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code adheres to [style guide](https://docs.getdbt.com/best-practices/how-we-style/0-how-we-style-our-dbt-projects)👀 and is **[DRY](https://docs.getdbt.com/terms/dry)**
- [ ] Code is well-commented (**please do not leave extraneous commentary in model code, if it is for the purpose of documentation, please relocate accordingly)
- [ ] Appropriate documentation has been provided (see `.yml.`, did `dbt docs generate` succeed?)
- [ ] New features are translatable or updates will not break up/downstream models
- [ ] Relevant documentation has been added or updated (i.e. `dbt docs` has been updated successfully on [Github Pages](code-dot-org.github.io/analytics/)
- [ ] Pull Request is labeled appropriately (eg. `chore/`, `feature/`, `fix/`)
- [ ] Follow-up work items (including potential tech debt) are tracked and linked (if applicable)

2024-02-27 22:40 UTC, nataliazm99 requested changes
Made some comments. Is the scope of this PR just to import dashboard_production.section_instructors? Next steps would be to combine with dim_sections and mark who is the teacher owner of the section, is that within the scope of this PR or a following one?

2024-02-27 22:40 UTC, nataliazm99 commented on dbt/models/staging/dashboard/stg_dashboard__users.sql
> -        studio_person_id,
The studio_person_id is needed for PD application tracking

2024-02-27 22:40 UTC, nataliazm99 commented on dbt/models/marts/users/dim_users.sql
>          users_pii.gender_group,
```suggestion
        users_pii.gender_group,
        users_pii.age_years,
```

2024-02-27 22:40 UTC, nataliazm99 commented on dbt/models/marts/users/dim_users.sql
> -        ug.is_international,
At this level of detail, country+ are not pii fields, it can't be de-identified

2024-02-27 22:40 UTC, nataliazm99 commented on dbt/models/staging/dashboard_pii/stg_dashboard_pii__users.sql
Why do we need two sources for sim_users? Why can't we pull everything from the pii schema? `dashboard.dashboard_production_pii.users` has the same information plus some columns as `dashboard.dashboard_production.users`, so using the _pii one as the sole source allows for less maintenance and more clarity

2024-02-27 22:40 UTC, nataliazm99 commented on dbt/models/staging/dashboard_pii/stg_dashboard_pii__users.sql
>          end as race_group,
@bakerfranke we had code for the race groups, right?

2024-02-27 22:40 UTC, nataliazm99 commented on dbt/models/marts/sections/dim_section_instructors.sql
> +        on section_instructors.section_id = courses.section_id)
`dim_course_structure` doesn't have section_id or any section information, it only includes information about courses/scripts/levels.
`dim_sections` have the `course_id` and `script_id` that are currently assigned to the section, but it doesn't have much meaning for analytical purposes and can be misleading, might be worth it to relabel as `current_assigned_course`, `current_assigned_script`.

I don't think this is meaningful information for dim_section_instructors. But if you want to include it, the correct join is ```on section_instructors.script_id = courses.script_id and section_instructors.course_id = courses.course_id ```
and note that there are plenty of scripts assigned with null course_id

2024-02-27 22:40 UTC, nataliazm99 commented on dbt/models/marts/sections/dim_section_instructors.sql
> +        courses.level_id,
```suggestion
--        courses.level_id,
```
The level of detail in dim_sections is by course/script. Level is a lower level of detail so adding it would multiply records unnecessarily

2024-02-27 22:40 UTC, nataliazm99 commented on dbt/models/marts/sections/dim_section_instructors.sql
> +-- scope: invited co-teachers
This is not limiting to 'invited co-teachers'.
```suggestion
-- scope: all teachers who created sections since 10/17/2023 when the co-teacher feature was added to the platform. 
```

2024-02-27 22:40 UTC, nataliazm99 commented on dbt/models/marts/sections/dim_section_instructors.sql
This is importing the data from dashboard_production.section_instructors, next steps would be to combine with dim_sections and mark who is the teacher owner of the section.

2024-02-27 23:23 UTC, jordan-springer commented on dbt/models/marts/sections/dim_section_instructors.sql
> +-- this is BP in terms of bringing in this data. we would then affect dim_teachers using this dim model.
best practice

2024-02-27 23:25 UTC, jordan-springer commented on dbt/models/staging/dashboard/stg_dashboard__section_instructors.sql
> +        instructor_id, -- teacher_id
I thought we were doing away with that concept?

2024-02-27 23:26 UTC, jordan-springer commented on dbt/models/staging/dashboard/stg_dashboard__section_instructors.sql
> +        updated_at
what do we need deleted for?

2024-02-28 14:20 UTC, nataliazm99 commented on dbt/models/staging/dashboard/stg_dashboard__section_instructors.sql
> +        instructor_id, -- teacher_id
I didn't think we were removing the concept, but instead using `user_id` when there is a single column having both teachers and students. In that case we use `user_id` and `user_type`. For example in `dim_user_activity` or in `dim_users`. But there are many cases when we will still need `teacher_id` and `student_id` because there will be many models where in one table we will have the teacher and their students, as one of the main uses of our analytical tables is that linkage between a teacher and their students.

2024-02-28 14:24 UTC, nataliazm99 commented on dbt/models/staging/dashboard/stg_dashboard__section_instructors.sql
> +        updated_at
If there is activity before they were deleted, that record is still valid. If teacher0 creates a section in Jan 1st, 2023, invites teacher1 as co-teacher on that date, deletes them as co-teacher on January 31st, and adds teacher2 as co-teacher in Feb 1st,  students' activity during January apply to teacher0 and teacher1, and students' activity during February apply to teacher0 and teacher2.

2024-03-05 20:10 UTC, closed without merging