Updating course_structure
code-dot-org/analytics pull request #99
Opened 2024-03-06 20:25 UTC by jordan-springer

# Description

Updating course_structure model based on changes to production

If relevant, include a description, screenshots, etc. of new behavior/model/update/...

## Links

Jira ticket(s): [dataops-559](https://codedotorg.atlassian.net/browse/DATAOPS-559)

## Testing story

- [ ] Does your change include appropriate tests on key columns?
      eg.
      - `not_null`
      - `unique`
      - `dbt_utils.unique_combination_of_columns: , ["value","value","value"...]

**Note: when submitting a new model for review please make sure the following have been tested:**

1. The model compiles (`dbt build -m 'your_model'`)
         or: _has the dbt Cloud job succeeded?_
3. The model runs (`dbt run -m 'your_model'`)
4. The model produces accessible data in the DW (`select 1 from 'your_model'`)

## Privacy

- [ ] 1.	Does this change involve the collection, use, or sharing of new Personal Data?
- [ ] 2.    Do these data exist in the appropriate schema(s)? 
- [ ] 3.	Does this change involve a new or changed use or sharing of existing Personal Data?
- [ ] 4.    Consider: will this data be visible on Tableau? will this data be surfaced in a report exported from Trevor?
- [ ] 5.    If yes to any of the above, please list the models, columns, and justification below:
      i.
      ii.
      iii. 

## PR Checklist:
**Note: if these are not all checked, the PR will be sent back.**

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code adheres to [style guide](https://docs.getdbt.com/best-practices/how-we-style/0-how-we-style-our-dbt-projects)👀 and is **[DRY](https://docs.getdbt.com/terms/dry)**
- [ ] Code is well-commented (**please do not leave extraneous commentary in model code, if it is for the purpose of documentation, please relocate accordingly)
- [ ] Appropriate documentation has been provided (see `.yml.`, did `dbt docs generate` succeed?)
- [ ] New features are translatable or updates will not break up/downstream models
- [ ] Relevant documentation has been added or updated (i.e. `dbt docs` has been updated successfully on [Github Pages](code-dot-org.github.io/analytics/)
- [ ] Pull Request is labeled appropriately (eg. `chore/`, `feature/`, `fix/`)
- [ ] Follow-up work items (including potential tech debt) are tracked and linked (if applicable)

2024-03-07 21:57 UTC, jordan-springer reviewed
ready for your review @nataliazm99

2024-03-15 20:33 UTC, nataliazm99 requested changes
I left comments in code, and here are some other findings:
1) Field `lesson_unplugged` is missing

2) Could be useful to flag levels who have sublevels by left joining `dashboard_production.parent_levels_child_levels` and adding these fields:
 ```
     , case when plcl.parent_level_id is not null then 'Y' else 'N' end parent_level
      , plcl.kind parent_level_kind
```

3) Differences with `dashboard.public.nzm_view_course_structure_redesigned`:
1. Assessments: has nulls for 2,865 records, should be 0
2. Course_name_long and course_name_short has nulls for 2,173 records that have values in my view
3. level_script_order is different for 594 records, e.g. level_id in (45530, 45229) 78 and 39 in my view, 77 and 38 in this model.

2024-04-05 16:49 UTC, jordan-springer commented on dbt/models/marts/courses/dim_course_structure.sql
>          sc.course_name_true,
outdated logic, will remove

2024-05-23 19:14 UTC, jordan-springer commented
Per review with NZM:
- remove `course_name_true` logic (see `case` statement)
- ensure we are not bringing in any _child_ levels (see last `left join`)

2024-05-23 19:29 UTC, nataliazm99 commented
- remove course_name_true logic for individual scripts. Use this case statement:

```
,
            CASE
	            WHEN json_extract_path_text(sc.properties, 'curriculum_umbrella', true) = '' THEN 'other'
	            ELSE LOWER(json_extract_path_text(sc.properties, 'curriculum_umbrella', true)) 
            END AS course_name_true,
```

- join `contained_levels` but only to indicate if it is a group level, don't bring in any child levels:
     1. add join statement: 
```            LEFT JOIN dashboard_production.contained_levels cl on lsl.level_id = cl.level_group_level_id 
```
2. add to the select:
```
             case
            	when cl.level_group_level_id is not null then 'Y'
            	else 'N' 
            end is_group_level,
            cl.contained_level_type group_level_type
```

2024-05-30 19:58 UTC, nataliazm99 requested changes
Overall it's good, matches the logic in the view and no meaningful changes in downstream models `dim_user_course_activity` and `dim_school_status`
The only issue that needs addressed is that field `lesson_unplugged` is still missing

2024-06-01 02:17 UTC, merged